"""Declarative argument schema for @preparse, driven by real type annotations.

A @preparse function declares each parameter's parser by annotating it with a
type from the vocabulary below — either a real runtime type (TiList, TiMatrix,
TiString, Thunk) or a PEP 695 ``type`` alias (Real, Numeric, Vectorized, …):

    @preparse_func
    def gcd(a: VectorizedReal, b: VectorizedReal) -> float: ...

Each vocabulary entry is a unique, hashable object used as a key into _REGISTRY,
which maps it to a parse function and a "kind" that drives vectorization.  Two
aliases may resolve to the same underlying type (TiListReal and TiListComplex
both alias TiList) yet stay distinct objects, so they select distinct parsers.

@preparse reads the signature (see schema_from_signature) and builds a tuple of
ArgSpec values.  Optionality and arity fall out of the signature: a parameter
with a default is optional; a ``*args`` parameter is variadic.

Parse functions all share the shape ``parse(args: ArgParser) -> value``.  Value
parsers are generated by make_validator(require_X): parse a general expression
via ArgParser.expr(), then assert its calculator data type with an O(1) guard.
Variable/name/thunk parsers delegate to the matching ArgParser method.

Runtime imports: core (types, validators, vectorize) and parser (ArgParser, whose
methods are referenced directly as the parse functions).
"""

import inspect
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum, auto
from functools import update_wrapper
from typing import Any, Callable

from core import (
	Variable, Thunk,
	TiList, TiMatrix, TiString,
	vectorize, matrix_vectorize,
	require_num, require_real,
	require_list, require_real_list, require_complex_list,
	require_matrix, require_string, require_list_or_matrix,
	require_vectorizable, require_vectorizable_real, require_matrix_vectorizable,
)
from environment import Environment
from parser import ArgParser



# ── Vocabulary: real types and PEP 695 aliases ────────────────────────────────
# Each name below is a unique, hashable object used as a key into _REGISTRY.  The
# calculator has only six runtime data types — Real, Complex, List, ComplexList,
# Matrix, String — and a vocabulary entry asserts exactly one shape of those.
# Refinements that are NOT true types (e.g. "is this an integer?") belong in the
# function body via require_int, not here.

# Scalars
type Real = float
type Complex = complex
type Numeric = Real | Complex

# Aggregates: TiList / TiMatrix / TiString are used directly as annotations.
type TiListReal = TiList        # list with no complex element
type TiListComplex = TiList     # list with at least one complex element
type ListOrMatrix = TiList | TiMatrix
type AnyValue = Any             # any value, parsed without a type guard (min/max)

# Vectorized slots: The body only ever sees scalars, so the annotation type is a
# scalar; the alias's presence signals @preparse to wrap the function so it maps
# element-wise over a list (Vectorized / VectorizedReal) or list-or-matrix
# (MatrixVectorized).  The parse-time guard still accepts the aggregate.
type Vectorized = Numeric
type VectorizedReal = Real
type MatrixVectorized = Real

# Variable references: All alias Variable but select different parse methods.
type NumericVar = Variable
type ListVar = Variable
type MatrixVar = Variable
type StringVar = Variable
type EquationVar = Variable
type AnyVar = Variable
type ListVarPrefixOptional = Variable

# Names and environment
type LabelName = str
type ProgramName = str
type Env = Environment


class _Arity(Enum):
	"""Parameter cardinality within a PreparsedFunc schema."""
	NORMAL   = auto()   # exactly one argument, required
	OPTIONAL = auto()   # one argument or absent; core default applies
	VARIADIC = auto()   # zero or more; greedily consumes remaining tokens


# ── Registry: vocabulary object → (parse function, kind) ──────────────────────
# `kind` is consumed once by @preparse to decide how (if at all) to wrap the core
# for vectorization.  env injects with no parse function (None).

def validated(require: Callable) -> Callable:
	"""Build a value parser: parse a general expression, then assert its type."""
	func = lambda args: require(args.expr())
	func.__name__ = f"expr_{require.__name__}"
	return func


_REGISTRY = {
	Numeric:               validated(require_num),
	Real:                  validated(require_real),
	TiList:                validated(require_list),
	TiListReal:            validated(require_real_list),
	TiListComplex:         validated(require_complex_list),
	TiMatrix:              validated(require_matrix),
	TiString:              validated(require_string),
	ListOrMatrix:          validated(require_list_or_matrix),
	Vectorized:            validated(require_vectorizable),
	VectorizedReal:        validated(require_vectorizable_real),
	MatrixVectorized:      validated(require_matrix_vectorizable),
	AnyValue:              ArgParser.expr,
	Thunk:                 ArgParser.thunk,
	NumericVar:            ArgParser.numeric_var,
	ListVar:               ArgParser.list_var,
	MatrixVar:             ArgParser.matrix_var,
	StringVar:             ArgParser.string_var,
	EquationVar:           ArgParser.equation_var,
	AnyVar:                ArgParser.any_var,
	ListVarPrefixOptional: ArgParser.list_var_prefix_optional,
	LabelName:             ArgParser.label_name,
	ProgramName:           ArgParser.program_name,
	Env:                   ArgParser.pass_env,
}

# ── ArgSpec and schema extraction ─────────────────────────────────────────────

@dataclass(frozen=True)
class ArgSpec:
	"""One parsed parameter: how to read its value, plus arity/kind metadata."""
	parse: Callable[[ArgParser], Any] | None
	arity: _Arity = _Arity.NORMAL

	@property
	def is_optional(self) -> bool:
		return self.arity is _Arity.OPTIONAL

	@property
	def is_variadic(self) -> bool:
		return self.arity is _Arity.VARIADIC

	def __repr__(self):
		return f"{self.parse.__name__}{'?' if self.is_optional else ''}{'*' if self.is_variadic else ''}"


# ── Call machinery: TiCall and the decorator forms ───────────────────────────
# A TiCall wraps a core function and knows how to drive an ArgParser to invoke it
# (call_with_parser).  Tokens hold these as their .function / .command.  The core
# stays a plain function, callable from Python via TiCall.__call__.

class TiCall(ABC):

	def __init__(self, func: Callable) -> None:
		self.func = func
		update_wrapper(self, func)

	def __call__(self, *args: Any) -> Any:
		return self.func(*args)

	@abstractmethod
	def call_with_parser(self, a: ArgParser) -> Any:
		pass


class forms_func(TiCall):
	"""Decorator for functions/commands that do their own parsing."""
	def call_with_parser(self, args: ArgParser):
		return self.func(args)


class no_arg_command(TiCall):
	"""Decorator for no-arg commands that consume the statement separator.

	The decorated function receives only the environment.  The decorator itself
	calls no_args() (raises TiSyntaxError if anything follows) then end().
	Use for Normal, Float, Radian, etc.
	"""
	def call_with_parser(self, args: Any) -> None:
		args.no_args()
		args.end_cmd()
		self.func(args.env)


class no_arg_bunch(TiCall):
	"""Decorator for no-arg commands that do NOT consume the separator.

	Does not check for surplus tokens — because the next token may be the start
	of the following command (e.g. ClockOnClockOn).  Simply runs the function
	and returns, leaving the parser exactly where it is so the main loop
	picks up the next statement naturally.
	Use for ClockOn, ClockOff, etc.
	"""
	def call_with_parser(self, args: Any) -> None:
		self.func(args.env)


class PreparsedFunc(TiCall):
	"""Wraps a plain core function with a declarative arg schema (see module docs).

	The schema is read from the core function's type annotations.  Each parse method guards
	its argument's true type at the token boundary, so the core needs no value
	validation wrapper — vectorization (if any) is the only wrapper:

	  * if any parameter is Vectorized/VectorizedReal, the core is wrapped in
	    @vectorize (maps element-wise over a TiList in any such slot);
	  * if a parameter is MatrixVectorized, the core is wrapped in
	    @matrix_vectorize (also maps over a TiMatrix).  At most one such parameter
	    is allowed, and it may not be combined with Vectorized parameters.

	The core stays a plain function, so functions remain callable from other Python
	code (composability) via TiCall.__call__.
	"""
	def __init__(self, core_func: Callable, finalizer: Callable[[ArgParser], None]) -> None:
		"""Build an ArgSpec schema from *func*'s annotated parameters.

		Each parameter must be annotated with a vocabulary type.  A parameter with a
		default becomes optional; a ``*args`` parameter becomes variadic.  The return
		annotation is ignored.
		"""
		annotations = inspect.get_annotations(core_func)
		is_vectorized = False
		mat_vec = 0
		schema = []
		for name, param in inspect.signature(core_func).parameters.items():
			if name not in annotations:
				raise TypeError(f"@preparse: {core_func.__name__}: parameter {name!r} has no annotation")

			arg_type = annotations[name]
			try:
				parse = _REGISTRY[arg_type]
			except (KeyError, TypeError):
				raise TypeError(f"@preparse: {core_func.__name__}: parameter {name!r} has unknown arg type {arg_type!r}")
			
			if arg_type in {Vectorized, VectorizedReal}:
				is_vectorized = True
			elif arg_type is MatrixVectorized:
				mat_vec += 1

			if param.kind is inspect.Parameter.VAR_POSITIONAL:
				arity = _Arity.VARIADIC
			elif param.default is not inspect.Parameter.empty:
				arity = _Arity.OPTIONAL
			else:
				arity = _Arity.NORMAL

			schema.append(ArgSpec(parse, arity))

		if mat_vec:
			if mat_vec > 1:
				raise TypeError(f"{core_func.__name__}: at most one matrix-vectorized parameter allowed")
			if is_vectorized:
				raise TypeError(f"{core_func.__name__}: cannot mix matrix-vectorized and vectorized parameters")
			func = matrix_vectorize(core_func)
		elif is_vectorized:
			func = vectorize(core_func)
		else:
			func = core_func

		super().__init__(func)
		self.schema = schema
		self.finalizer = finalizer

	def call_with_parser(self, args: ArgParser):
		values = args.take(*self.schema)
		self.finalizer(args)
		return args.env.guard_real(values, self.func(*values))
	
	def __repr__(self):
		return f"preparsed({self.func.__name__}, {self.schema}, {self.finalizer.__name__})"


def _preparse(finalizer: Callable[[ArgParser], None]):
	"""Return a decorator that wraps a core function as a PreparsedFunc.

	Prefer the named aliases below over calling this directly:
	  preparse_func     — expression functions  (end_func, eats `)`              )
	  preparse_cmd      — no-paren commands     (end_cmd, eats trailing separator)
	  preparse_cmd_func — paren commands        (end_paren_cmd, eats `) + sep`   )
	  preparse_bunch    — bunching commands     (no finalizer, e.g. DelVar       )
	"""
	def decorator(core_func: Callable) -> PreparsedFunc:
		return PreparsedFunc(core_func, finalizer)
	return decorator


def _noop(_env): pass


preparse_func     = _preparse(ArgParser.end_func)
preparse_cmd      = _preparse(ArgParser.end_cmd)
preparse_cmd_func = _preparse(ArgParser.end_paren_cmd)
preparse_bunch    = _preparse(_noop)
