"""Declarative argument schema for @preparse, driven by real type annotations.

A @preparse function declares each parameter's parser by annotating it with a
type from the vocabulary below — either a real runtime type (TiList, TiMatrix,
TiString, Thunk) or a PEP 695 ``type`` alias (Real, Numeric, Vectorized, …):

    @preparse_func
    def gcd(a: VectorizedReal, b: VectorizedReal) -> float: ...

Each vocabulary entry is a unique, hashable object used as a key into _REGISTRY,
which maps it to a parse function and a "kind" that drives vectorization.  Two
aliases may resolve to the same underlying type (TiListReal and TiListComplex
both alias TiList) yet stay distinct objects, so they select distinct parsers.

@preparse reads the signature (see schema_from_signature) and builds a tuple of
ArgSpec values.  Optionality and arity fall out of the signature: a parameter
with a default is optional; a ``*args`` parameter is variadic.

Parse functions all share the shape ``parse(args: ArgParser) -> value``.  Value
parsers are generated by make_validator(require_X): parse a general expression
via ArgParser.expr(), then assert its calculator data type with an O(1) guard.
Variable/name/thunk parsers delegate to the matching ArgParser method.

Runtime imports are deliberately light (tiobjects, core, decorators); Environment
and ArgParser stay behind TYPE_CHECKING, so importing the vocabulary never drags
in the heavyweight parser/environment modules (avoiding import cycles).
"""
from __future__ import annotations

import inspect
from dataclasses import dataclass
from enum import Enum, auto
from operator import methodcaller
from typing import Any, Callable, TYPE_CHECKING

from core import (
	Variable, Thunk,
	TiList, TiMatrix, TiString,
	require_num, require_real,
	require_list, require_real_list, require_complex_list,
	require_matrix, require_str, require_list_or_matrix,
	require_vectorizable, require_vectorizable_real, require_matrix_vectorizable,
)
from decorators import TiCall, vectorize, matrix_vectorize

if TYPE_CHECKING:
	from environment import Environment
	from parser import ArgParser


# ── Vocabulary: real types and PEP 695 aliases ────────────────────────────────
# Each name below is a unique, hashable object used as a key into _REGISTRY.  The
# calculator has only six runtime data types — Real, Complex, List, ComplexList,
# Matrix, String — and a vocabulary entry asserts exactly one shape of those.
# Refinements that are NOT true types (e.g. "is this an integer?") belong in the
# function body via require_int, not here.

# Scalars.
type Real = float
type Complex = complex
type Numeric = Real | Complex

# Aggregates.  TiList / TiMatrix / TiString are used directly as annotations.
type TiListReal = TiList        # list with no complex element
type TiListComplex = TiList     # list with at least one complex element
type ListOrMatrix = TiList | TiMatrix
type AnyValue = Any             # any value, parsed without a type guard (min/max)

# Vectorized slots.  The body only ever sees scalars, so the annotation type is a
# scalar; the alias's presence signals @preparse to wrap the function so it maps
# element-wise over a list (Vectorized / VectorizedReal) or list-or-matrix
# (MatrixVectorized).  The parse-time guard still accepts the aggregate.
type Vectorized = Numeric
type VectorizedReal = Real
type MatrixVectorized = Real

# Variable references.  All alias Variable but select different parse methods.
type NumericVar = Variable
type ListVar = Variable
type MatrixVar = Variable
type StringVar = Variable
type EquationVar = Variable
type AnyVar = Variable
type ListVarPrefixOptional = Variable

# Names and environment.
type LabelName = str
type ProgramName = str
type Env = Environment          # injected from ArgParser.env; consumes no token


# ── Parse functions: parse(args: ArgParser) -> value ──────────────────────────

def make_validator(require: Callable) -> Callable:
	"""Build a value parser: parse a general expression, then assert its type."""
	return lambda args: require(args.expr())

parse_numeric           = make_validator(require_num)
parse_real              = make_validator(require_real)
parse_list              = make_validator(require_list)
parse_real_list         = make_validator(require_real_list)
parse_complex_list      = make_validator(require_complex_list)
parse_matrix            = make_validator(require_matrix)
parse_string            = make_validator(require_str)
parse_list_or_matrix    = make_validator(require_list_or_matrix)
parse_vectorized        = make_validator(require_vectorizable)
parse_vectorized_real   = make_validator(require_vectorizable_real)
parse_matrix_vectorized = make_validator(require_matrix_vectorizable)
parse_value             = methodcaller('expr')   # no guard

# Variable / name / thunk parsers delegate to the matching ArgParser method.
parse_thunk          = methodcaller('thunk')
parse_numeric_var    = methodcaller('numeric_var')
parse_list_var       = methodcaller('list_var')
parse_matrix_var     = methodcaller('matrix_var')
parse_string_var     = methodcaller('string_var')
parse_equation_var   = methodcaller('equation_var')
parse_any_var        = methodcaller('any_var')
parse_list_var_prefix_optional = methodcaller('list_var_prefix_optional')
parse_label_name     = methodcaller('label_name')
parse_program_name   = methodcaller('program_name')


# ── Kind and Arity enums ──────────────────────────────────────────────────────

class _Role(Enum):
	"""Drives vectorization wrapping in PreparsedFunc (see _REGISTRY)."""
	VALUE  = auto()   # plain value: no wrapping
	ENV    = auto()   # inject ArgParser.env; no token consumed
	VEC    = auto()   # element-wise over TiList (and scalars)
	MATVEC = auto()   # element-wise over TiMatrix or TiList (and scalars)


class _Arity(Enum):
	"""Parameter cardinality within a PreparsedFunc schema."""
	NORMAL   = auto()   # exactly one argument, required
	OPTIONAL = auto()   # one argument or absent; core default applies
	VARIADIC = auto()   # zero or more; greedily consumes remaining tokens


# ── Registry: vocabulary object → (parse function, kind) ──────────────────────
# `kind` is consumed once by @preparse to decide how (if at all) to wrap the core
# for vectorization.  env injects with no parse function (None).

_REGISTRY = {
	Numeric:               (parse_numeric, _Role.VALUE),
	Real:                  (parse_real, _Role.VALUE),
	TiList:                (parse_list, _Role.VALUE),
	TiListReal:            (parse_real_list, _Role.VALUE),
	TiListComplex:         (parse_complex_list, _Role.VALUE),
	TiMatrix:              (parse_matrix, _Role.VALUE),
	TiString:              (parse_string, _Role.VALUE),
	ListOrMatrix:          (parse_list_or_matrix, _Role.VALUE),
	AnyValue:              (parse_value, _Role.VALUE),
	Vectorized:            (parse_vectorized, _Role.VEC),
	VectorizedReal:        (parse_vectorized_real, _Role.VEC),
	MatrixVectorized:      (parse_matrix_vectorized, _Role.MATVEC),
	Thunk:                 (parse_thunk, _Role.VALUE),
	NumericVar:            (parse_numeric_var, _Role.VALUE),
	ListVar:               (parse_list_var, _Role.VALUE),
	MatrixVar:             (parse_matrix_var, _Role.VALUE),
	StringVar:             (parse_string_var, _Role.VALUE),
	EquationVar:           (parse_equation_var, _Role.VALUE),
	AnyVar:                (parse_any_var, _Role.VALUE),
	ListVarPrefixOptional: (parse_list_var_prefix_optional, _Role.VALUE),
	LabelName:             (parse_label_name, _Role.VALUE),
	ProgramName:           (parse_program_name, _Role.VALUE),
	Env:                   (None, _Role.ENV),
}


# ── ArgSpec and schema extraction ─────────────────────────────────────────────

@dataclass(frozen=True)
class ArgSpec:
	"""One parsed parameter: how to read its value, plus arity/kind metadata."""
	parse: Any                      # Callable[[ArgParser], value]; None ⇒ inject env
	role: _Role = _Role.VALUE       # drives vectorization wrapping (see PreparsedFunc)
	arity: _Arity = _Arity.NORMAL   # NORMAL / OPTIONAL / VARIADIC

	def __repr__(self):
		name = 'env' if self.parse is None else getattr(self.parse, '__name__', 'parse')
		flags = {_Arity.OPTIONAL: '?', _Arity.VARIADIC: '*'}.get(self.arity, '')
		return f"{name}{flags}"


def schema_from_signature(func) -> tuple:
	"""Build an ArgSpec schema from *func*'s annotated parameters.

	Each parameter must be annotated with a vocabulary type.  A parameter with a
	default becomes optional; a ``*args`` parameter becomes variadic.  The return
	annotation is ignored.

	Annotations are read with ``eval_str=True`` so this works whether or not the
	defining module uses ``from __future__ import annotations`` — the vocabulary
	names just have to be importable there (they are).
	"""
	annotations = inspect.get_annotations(func, eval_str=True)
	schema = []
	for name, p in inspect.signature(func).parameters.items():
		if name not in annotations:
			raise TypeError(f"@preparse: {func.__name__}: parameter {name!r} has no annotation")
		ann = annotations[name]
		try:
			parse, role = _REGISTRY[ann]
		except (KeyError, TypeError):
			raise TypeError(
				f"@preparse: {func.__name__}: parameter {name!r} has unknown arg type {ann!r}"
			)
		if p.kind is inspect.Parameter.VAR_POSITIONAL:
			arity = _Arity.VARIADIC
		elif p.default is not inspect.Parameter.empty:
			arity = _Arity.OPTIONAL
		else:
			arity = _Arity.NORMAL
		schema.append(ArgSpec(parse, role, arity))
	return tuple(schema)


# ── @preparse ─────────────────────────────────────────────────────────────────

class Finalize(Enum):
	"""Which ArgParser end method PreparsedFunc calls after parsing.

	  FUNC      — end_func()       expression functions; eats ), no separator
	  CMD       — end_cmd()        no-paren commands; eats trailing separator
	  CMD_FUNC  — end_paren_cmd()  paren commands; eats ) + separator
	  NONE      — (nothing)        leaves the parser untouched so the command
	                               bunches with whatever follows (e.g. DelVar)
	"""
	FUNC = auto()
	CMD = auto()
	CMD_FUNC = auto()
	NONE = auto()


# Maps each Finalize mode to a callable f(parser) that finalizes the argument list.
def _noop(_): pass

_END_METHOD = {
	Finalize.FUNC:     methodcaller('end_func'),
	Finalize.CMD:      methodcaller('end_cmd'),
	Finalize.CMD_FUNC: methodcaller('end_paren_cmd'),
	Finalize.NONE:     _noop,
}


class PreparsedFunc(TiCall):
	"""Wraps a plain core function with a declarative arg schema (see module docs).

	The schema is read from the core's type annotations.  Each parse method guards
	its argument's true type at the token boundary, so the core needs no value
	validation wrapper — vectorization (if any) is the only wrapper:

	  * if any parameter is Vectorized/VectorizedReal, the core is wrapped in
	    @vectorize (maps element-wise over a TiList in any such slot);
	  * if a parameter is MatrixVectorized, the core is wrapped in
	    @matrix_vectorize (also maps over a TiMatrix).  At most one such parameter
	    is allowed, and it may not be combined with Vectorized parameters.

	The core stays a plain function, so functions remain callable from other Python
	code (composability) via TiCall.__call__.
	"""
	def __init__(self, core: Callable, end: Finalize = Finalize.FUNC) -> None:
		schema = schema_from_signature(core)
		roles = [s.role for s in schema]
		if _Role.MATVEC in roles:
			if roles.count(_Role.MATVEC) > 1:
				raise TypeError(f"{core.__name__}: at most one matrix-vectorized parameter allowed")
			if _Role.VEC in roles:
				raise TypeError(f"{core.__name__}: cannot mix matrix-vectorized and vectorized parameters")
			func = matrix_vectorize(core)
		elif _Role.VEC in roles:
			func = vectorize(core)
		else:
			func = core

		super().__init__(func)
		self.schema = schema
		self.end_method = _END_METHOD[end]

	def call_with_parser(self, args: ArgParser):
		values = args.take(*self.schema)
		self.end_method(args)
		return args.env.guard_real(values, self.func(*values))


def preparse(end: Finalize):
	"""Return a decorator that wraps a core function as a PreparsedFunc.

	Prefer the named aliases below over calling this directly:
	  preparse_func     — expression functions  (end_func, eats `)`              )
	  preparse_cmd      — no-paren commands     (end_cmd, eats trailing separator)
	  preparse_cmd_func — paren commands        (end_paren_cmd, eats `) + sep`   )
	  preparse_bunch    — bunching commands     (no finalizer, e.g. DelVar       )

	Use this directly only when you need to select a Finalize mode dynamically.
	"""

	def decorator(core: Callable) -> PreparsedFunc:
		return PreparsedFunc(core, end)
	return decorator


# Named decorator aliases — preferred over calling preparse() directly.
preparse_func     = preparse(Finalize.FUNC)
preparse_cmd      = preparse(Finalize.CMD)
preparse_cmd_func = preparse(Finalize.CMD_FUNC)
preparse_bunch    = preparse(Finalize.NONE)
