from dataclasses import dataclass
import itertools


@dataclass
class Token:
	code: bytes
	key: str
	text: str
	category: str
	desc: str
	alias: set[str]
	is_function: bool


def token(code: bytes, text: str, category: str, desc: str, alt: str | set[str] | None = None, key: str | None = None):
	alias = {text}
	if isinstance(alt, str):
		alias.add(alt)
	elif alt is not None:
		alias.update(alt)
	return Token(code, key, text, category, desc, alias, text.endswith('('))


TOKENS: list[Token] = [
	# One-byte tokens
	token(b'\x01', "►DMS",        "math",     "Converts a decimal angle to degree-minute-second display", alt='to-DMS'),
	token(b'\x02', "►Dec",        "math",     "Converts a fraction or expression to decimal form", alt='to-Dec'),
	token(b'\x03', "►Frac",       "math",     "Converts a decimal to the simplest fraction form", alt='to-Frac'),
	token(b'\x04', "→",           "operator", "Stores a value into a variable", key='@',                   alt=("->", 'store')),
	token(b'\x05', "Boxplot",     "stat",     "Selects the standard box-and-whisker plot type for a stat plot"),
	token(b'\x06', "[",           "operator", "Opens a matrix literal", key='['),
	token(b'\x07', "]",           "operator", "Closes a matrix literal", key=']'),
	token(b'\x08', "{",           "operator", "Opens a list literal", key='{'),
	token(b'\x09', "}",           "operator", "Closes a list literal", key='}'),
	token(b'\x0a', "ʳ",           "math",     "Radian angle-unit suffix",                                  alt="rad"),
	token(b'\x0b', "°",           "math",     "Degree angle-unit suffix",                                  alt="deg"),
	token(b'\x0c', "⁻¹",          "math",     "Computes the multiplicative inverse (reciprocal)",           alt=("inv", '^-1')),
	token(b'\x0d', "²",           "math",     "Squares a value or matrix",                                 alt="^2"),
	token(b'\x0e', "ᵀ",           "matrix",   "Returns the transpose of a matrix",                         alt=("T", 'transpose')),
	token(b'\x0f', "³",           "math",     "Cubes a value",                                             alt="^3"),
	token(b'\x10', "(",           "operator", "Opens a parenthetical expression", key='('),
	token(b'\x11', ")",           "operator", "Closes a parenthetical expression", key=')'),
	token(b'\x12', "round(",      "math",     "Rounds a number to a specified number of decimal places"),
	token(b'\x13', "pxl-Test(",   "io",       "Returns 1 if the specified screen pixel is on, 0 otherwise"),
	token(b'\x14', "augment(",    "matrix",   "Concatenates two matrices or two lists horizontally"),
	token(b'\x15', "rowSwap(",    "matrix",   "Swaps two rows of a matrix"),
	token(b'\x16', "row+(",       "matrix",   "Adds one matrix row to another and stores the result"),
	token(b'\x17', "*row(",       "matrix",   "Multiplies a matrix row by a scalar"),
	token(b'\x18', "*row+(",      "matrix",   "Multiplies a matrix row by a scalar and adds it to another row"),
	token(b'\x19', "max(",        "math",     "Returns the maximum of two values or of all elements in a list"),
	token(b'\x1a', "min(",        "math",     "Returns the minimum of two values or of all elements in a list"),
	token(b'\x1b', "R►Pr(",       "math",     "Converts rectangular coordinates to the r component of polar coordinates", alt='R-to-Pr'),
	token(b'\x1c', "R►Pθ(",       "math",     "Converts rectangular coordinates to the θ component of polar coordinates", alt='R-to-P-theta'),
	token(b'\x1d', "P►Rx(",       "math",     "Converts polar coordinates to the x component of rectangular coordinates", alt='R-to-Px'),
	token(b'\x1e', "P►Ry(",       "math",     "Converts polar coordinates to the y component of rectangular coordinates", alt='R-to-Py'),
	token(b'\x1f', "median(",     "stat",     "Returns the median of a list of values"),
	token(b'\x20', "randM(",      "matrix",   "Generates a random matrix of given dimensions with integer entries"),
	token(b'\x21', "mean(",       "stat",     "Returns the arithmetic mean of a list"),
	token(b'\x22', "solve(",      "math",     "Numerically solves an equation for a specified variable near a given guess"),
	token(b'\x23', "seq(",        "list",     "Generates a list by evaluating an expression over a range of values"),
	token(b'\x24', "fnInt(",      "math",     "Numerically approximates the definite integral of a function"),
	token(b'\x25', "nDeriv(",     "math",     "Numerically approximates the derivative of a function at a point"),
	token(b'\x27', "fMin(",       "math",     "Finds the x-value at the minimum of a function on an interval"),
	token(b'\x28', "fMax(",       "math",     "Finds the x-value at the maximum of a function on an interval"),
	token(b'\x29', " ",           "operator", "Space character used in strings and output", key=' '),
	token(b'\x2a', '"',           "string",   "Delimits a string literal", key='"'),
	token(b'\x2b', ",",           "operator", "Separates arguments in a function call", key=','),
	token(b'\x2c', "𝑖",           "math",     "The imaginary unit, equal to √(−1)",                        alt="imaginary"),  # maybe-key
	token(b'\x2d', "!",           "math",     "Computes the factorial of a non-negative integer", key='!'),
	token(b'\x2e', "CubicReg",    "stat",     "Fits a cubic regression model to data"),
	token(b'\x2f', "QuartReg",    "stat",     "Fits a quartic regression model to data"),
	*[token(bytes([0x30 + i]), chr(0x41 + i), "number", f"Digit {chr(0x30 + i)}", key=chr(0x30 + i)) for i in range(10)],
	token(b'\x3a', ".",           "number",   "Decimal point in numeric literals", key='.'),
	token(b'\x3b', "ᴇ",           "math",     "Scientific notation exponent (×10^n)",                      alt="E"),
	token(b'\x3c', "or",          "operator", "Boolean OR operator"),
	token(b'\x3d', "xor",         "operator", "Boolean XOR operator"),
	token(b'\x3e', ":",           "control",  "Statement separator", key=':'),
	token(b'\x3f', "↵",     "control", "Program line separator (newline)", alt="newline"),
	token(b'\x40', "and",         "operator", "Boolean AND operator"),
	# Variables A–Z (0x41–0x5A)
	*[token(bytes([0x41 + i]), chr(0x41 + i), "variable", f"Real variable {chr(0x41 + i)}", key=chr(0x41 + i)) for i in range(26)],
	token(b'\x5b', "θ",           "variable", "Variable theta",                                            alt="theta"),  # maybe-key
	token(b'\x5f', "prgm",        "control",  "Calls a named subprogram"),
	token(b'\x64', "Radian",      "control",  "Sets angle mode to radians"),
	token(b'\x65', "Degree",      "control",  "Sets angle mode to degrees"),
	token(b'\x66', "Normal",      "control",  "Sets display notation to normal (non-scientific)"),
	token(b'\x67', "Sci",         "control",  "Sets display notation to scientific notation"),
	token(b'\x68', "Eng",         "control",  "Sets display notation to engineering notation"),
	token(b'\x69', "Float",       "control",  "Sets the display to floating-point (full) decimal mode"),
	token(b'\x6a', "=",           "operator", "Tests equality between two values", key='='),
	token(b'\x6b', "<",           "operator", "Tests whether the left operand is less than the right", key='<'),
	token(b'\x6c', ">",           "operator", "Tests whether the left operand is greater than the right", key='>'),
	token(b'\x6d', "≤",           "operator", "Less than or equal to",                                     alt="<="),
	token(b'\x6e', "≥",           "operator", "Greater than or equal to",                                  alt=">="),
	token(b'\x6f', "≠",           "operator", "Not equal to",                                              alt="!="),
	token(b'\x70', "+",           "operator", "Adds two numbers, matrices, or lists", key='+'),
	token(b'\x71', "-",           "operator", "Subtraction", key='-'),
	token(b'\x72', "Ans",         "variable", "Contains the result of the last evaluated expression"),  # maybe-key
	token(b'\x73', "Fix",         "control",  "Sets the display to a fixed number of decimal places"),
	token(b'\x74', "Horiz",       "control",  "Sets the screen to horizontal split mode (graph + home)"),
	token(b'\x75', "Full",        "control",  "Sets the screen to full (non-split) mode"),
	token(b'\x76', "Func",        "control",  "Sets graphing mode to function (Y=) mode"),
	token(b'\x77', "Param",       "control",  "Sets graphing mode to parametric mode"),
	token(b'\x78', "Polar",       "control",  "Sets graphing mode to polar mode"),
	token(b'\x79', "Seq",         "control",  "Sets graphing mode to sequence mode"),
	token(b'\x7a', "IndpntAuto",  "control",  "Sets table independent variable to auto mode"),
	token(b'\x7b', "IndpntAsk",   "control",  "Sets table independent variable to ask mode"),
	token(b'\x7c', "DependAuto",  "control",  "Sets table dependent variable to auto mode"),
	token(b'\x7d', "DependAsk",   "control",  "Sets table dependent variable to ask mode"),
	token(b'\x7f', "<squaremark>",   "control",  "", alt='square-mark'),
	token(b'\x80', "<crossmark>",   "control",  "", alt='cross-mark'),
	token(b'\x81', "<dotmark>",   "control",  "", alt='dot-mark'),
	token(b'\x82', "*",           "operator", "Multiplies two numbers, scalars by matrices, or lists", key='*'),
	token(b'\x83', "/",           "operator", "Division", key='/'),
	token(b'\x84', "Trace",       "io",       "Activates trace mode on the graph screen"),
	token(b'\x85', "ClrDraw",     "io",       "Clears all drawn objects from the graph screen"),
	token(b'\x86', "ZStandard",   "io",       "Sets the graphing window to standard zoom (±10 on both axes)"),
	token(b'\x87', "ZTrig",       "io",       "Sets the graphing window optimized for trigonometric functions"),
	token(b'\x88', "ZBox",        "io",       "Zooms in on a rectangular region you draw on the graph"),
	token(b'\x89', "Zoom In",     "io",       "Zooms in on the graph centered at the cursor position",      alt="ZoomIn"),
	token(b'\x8a', "Zoom Out",    "io",       "Zooms out on the graph centered at the cursor position",     alt="ZoomOut"),
	token(b'\x8b', "ZSquare",     "io",       "Adjusts the window so pixels are square (equal aspect ratio)"),
	token(b'\x8c', "ZInteger",    "io",       "Sets the zoom so each pixel represents one integer unit"),
	token(b'\x8d', "ZPrevious",   "io",       "Restores the previous graphing window settings"),
	token(b'\x8e', "ZDecimal",    "io",       "Sets the window so each pixel is 0.1 unit wide"),
	token(b'\x8f', "ZoomStat",    "io",       "Adjusts the graphing window to show all stat plot data"),
	token(b'\x90', "ZoomRcl",     "io",       "Restores a previously stored zoom window"),
	token(b'\x91', "PrintScreen", "io", "Prints the current screen to a connected printer (legacy)"),
	token(b'\x92', "ZoomSto",     "io",       "Saves the current graphing window settings"),
	token(b'\x93', "Text(",       "io",       "Draws text on the graph screen at specified pixel coordinates"),
	token(b'\x94', "nPr",         "math",     "Computes the number of permutations of n things taken r at a time"),
	token(b'\x95', "nCr",         "math",     "Computes the number of combinations of n things taken r at a time"),
	token(b'\x96', "FnOn",        "control",  "Turns on one or more Y= functions for graphing"),
	token(b'\x97', "FnOff",       "control",  "Turns off one or more Y= functions for graphing"),
	token(b'\x98', "StorePic",    "io",       "Saves the current graph screen image to a Pic variable"),
	token(b'\x99', "RecallPic",   "io",       "Draws a previously stored Pic variable on the graph screen"),
	token(b'\x9a', "StoreGDB",    "io",       "Saves the current graph database to a GDB variable"),
	token(b'\x9b', "RecallGDB",   "io",       "Restores a graph database from a GDB variable"),
	token(b'\x9c', "Line(",       "io",       "Draws or erases a line between two points on the graph screen"),
	token(b'\x9d', "Vertical",    "io",       "Draws a vertical line at a specified x-value on the graph screen"),
	token(b'\x9e', "Pt-On(",      "io",       "Turns on a point on the graph screen at specified coordinates"),
	token(b'\x9f', "Pt-Off(",     "io",       "Turns off a point on the graph screen at specified coordinates"),
	token(b'\xa0', "Pt-Change(",  "io",       "Toggles a point on the graph screen at specified coordinates"),
	token(b'\xa1', "Pxl-On(",     "io",       "Turns on a pixel at specified row and column coordinates"),
	token(b'\xa2', "Pxl-Off(",    "io",       "Turns off a pixel at specified row and column coordinates"),
	token(b'\xa3', "Pxl-Change(", "io",       "Toggles a pixel at specified row and column coordinates"),
	token(b'\xa4', "Shade(",      "io",       "Shades the area between two functions on the graph screen"),
	token(b'\xa5', "Circle(",     "io",       "Draws a circle on the graph screen with a given center and radius"),
	token(b'\xa6', "Horizontal",  "io",       "Draws a horizontal line at a specified y-value on the graph screen"),
	token(b'\xa7', "Tangent(",    "io",       "Draws the tangent line to a function at a specified x-value"),
	token(b'\xa8', "DrawInv",     "io",       "Draws the inverse of a function on the graph screen"),
	token(b'\xa9', "DrawF",       "io",       "Draws a function on the graph screen"),
	token(b'\xab', "rand",        "math",     "Generates a uniformly random real number between 0 and 1"),
	token(b'\xac', "π",           "math",     "The mathematical constant pi (≈3.14159...)",                 alt="pi"),  # maybe-key
	token(b'\xad', "getKey",      "io",       "Returns the keycode of the last key pressed, or 0 if none"),
	token(b'\xae', "'",           "string",   "Apostrophe / single-quote character",                        alt="apostrophe", key="'"),
	token(b'\xaf', "?",           "io",       "Displays a question-mark prompt to wait for user input (legacy)", key='?'),
	token(b'\xb0', "−",           "math",     "Negates a value (unary minus)",                              alt=('~', "neg"), key='~'),
	token(b'\xb1', "int(",        "math",     "Returns the greatest integer less than or equal to a number (floor)"),
	token(b'\xb2', "abs(",        "math",     "Returns the absolute value of a number"),
	token(b'\xb3', "det(",        "matrix",   "Returns the determinant of a square matrix"),
	token(b'\xb4', "identity(",   "matrix",   "Returns an n×n identity matrix"),
	token(b'\xb5', "dim(",        "list",     "Returns the length of a list or the dimensions of a matrix"),
	token(b'\xb6', "sum(",        "list",     "Returns the sum of all elements in a list"),
	token(b'\xb7', "prod(",       "list",     "Returns the product of all elements in a list"),
	token(b'\xb8', "not(",        "operator", "Returns the boolean NOT of a value (0→1, nonzero→0)"),
	token(b'\xb9', "iPart(",      "math",     "Returns the integer part (truncation toward zero) of a number"),
	token(b'\xba', "fPart(",      "math",     "Returns the fractional part of a number"),
	token(b'\xbc', "√(",          "math",     "Returns the square root of a non-negative number",           alt=("sqrt(", 'squareroot')),
	token(b'\xbd', "³√(",         "math",     "Returns the cube root of a number",                         alt=("cbrt(", 'cuberoot')),
	token(b'\xbe', "ln(",         "math",     "Returns the natural logarithm of a positive number"),
	token(b'\xbf', "e^(",         "math",     "Returns e raised to the specified power"),
	token(b'\xc0', "log(",        "math",     "Returns the base-10 logarithm of a positive number"),
	token(b'\xc1', "10^(",        "math",     "Returns 10 raised to the specified power"),
	token(b'\xc2', "sin(",        "trig",     "Returns the sine of an angle"),
	token(b'\xc3', "sin⁻¹(",      "trig",     "Returns the arcsine (inverse sine) of a value",             alt="arcsin("),
	token(b'\xc4', "cos(",        "trig",     "Returns the cosine of an angle"),
	token(b'\xc5', "cos⁻¹(",      "trig",     "Returns the arccosine (inverse cosine) of a value",         alt="arccos("),
	token(b'\xc6', "tan(",        "trig",     "Returns the tangent of an angle"),
	token(b'\xc7', "tan⁻¹(",      "trig",     "Returns the arctangent (inverse tangent) of a value",       alt="arctan("),
	token(b'\xc8', "sinh(",       "math",     "Returns the hyperbolic sine of a value"),
	token(b'\xc9', "sinh⁻¹(",     "math",     "Returns the inverse hyperbolic sine of a value",             alt="arcsinh("),
	token(b'\xca', "cosh(",       "math",     "Returns the hyperbolic cosine of a value"),
	token(b'\xcb', "cosh⁻¹(",     "math",     "Returns the inverse hyperbolic cosine of a value",          alt="arccosh("),
	token(b'\xcc', "tanh(",       "math",     "Returns the hyperbolic tangent of a value"),
	token(b'\xcd', "tanh⁻¹(",     "math",     "Returns the inverse hyperbolic tangent of a value",         alt="arctanh("),
	token(b'\xce', "If ",          "control",  "Conditionally executes the next statement or Then/Else block"),
	token(b'\xcf', "Then",        "control",  "Begins the body of an If block when the condition is true"),
	token(b'\xd0', "Else",        "control",  "Begins the alternate body of an If-Then block when the condition is false"),
	token(b'\xd1', "While ",       "control",  "Repeats a block as long as a condition remains true"),
	token(b'\xd2', "Repeat ",      "control",  "Repeats a block until a condition becomes true (always runs at least once)"),
	token(b'\xd3', "For(",        "control",  "Iterates a variable from a start to an end value by a step"),
	token(b'\xd4', "End",         "control",  "Marks the end of an If-Then, While, Repeat, or For block"),
	token(b'\xd5', "Return",      "control",  "Exits the current program or subprogram and returns to the caller"),
	token(b'\xd6', "Lbl ",         "control",  "Defines a label that can be targeted by Goto"),
	token(b'\xd7', "Goto ",        "control",  "Jumps execution unconditionally to a specified label"),
	token(b'\xd8', "Pause ",       "control",  "Pauses program execution until the user presses ENTER"),
	token(b'\xd9', "Stop",        "control",  "Terminates program execution immediately"),
	token(b'\xda', "IS>(",        "control",  "Increments a variable and skips the next statement if it exceeds a limit"),
	token(b'\xdb', "DS<(",        "control",  "Decrements a variable and skips the next statement if it goes below a limit"),
	token(b'\xdc', "Input ",       "io",       "Prompts the user to enter a value or string"),
	token(b'\xdd', "Prompt ",      "io",       "Prompts the user to enter values for one or more variables"),
	token(b'\xde', "Disp ",        "io",       "Displays values or strings on the home screen"),
	token(b'\xdf', "DispGraph",   "io",       "Displays the current graph screen"),
	token(b'\xe0', "Output(",     "io",       "Displays a value or string at a specific row and column on the home screen"),
	token(b'\xe1', "ClrHome",     "io",       "Clears the home screen"),
	token(b'\xe2', "Fill(",       "list",     "Fills all elements of a list or matrix with a specified value"),
	token(b'\xe3', "SortA(",      "list",     "Sorts a list in ascending order in-place"),
	token(b'\xe4', "SortD(",      "list",     "Sorts a list in descending order in-place"),
	token(b'\xe5', "DispTable",   "io",       "Displays the function table"),
	token(b'\xe6', "Menu(",       "io",       "Displays a menu and branches to a label based on user selection"),
	token(b'\xe7', "Send(",       "io",       "Sends a list to a connected CBL/CBR device"),
	token(b'\xe8', "Get(",        "io",       "Retrieves a list from a connected CBL/CBR device"),
	token(b'\xe9', "PlotsOn",     "stat",     "Turns on one or all stat plots"),
	token(b'\xea', "PlotsOff",    "stat",     "Turns off one or all stat plots"),
	token(b'\xeb', "∟",           "list",     "Prefix token used to name user-defined lists (e.g., ∟NAME)",  alt="list-prefix", key='#'),
	token(b'\xec', "Plot1(",      "stat",     "Configures stat Plot 1 with a type and data sources"),
	token(b'\xed', "Plot2(",      "stat",     "Configures stat Plot 2 with a type and data sources"),
	token(b'\xee', "Plot3(",      "stat",     "Configures stat Plot 3 with a type and data sources"),
	token(b'\xf0', "^",           "math",     "Raises the left operand to the power of the right operand", key='^'),
	token(b'\xf1', "×√",          "math",     "Computes the x-th root of a value",                          alt="xroot"),
	token(b'\xf2', "1-Var Stats", "stat",     "Computes one-variable statistics for a dataset"),
	token(b'\xf3', "2-Var Stats", "stat",     "Computes two-variable statistics for a paired dataset"),
	token(b'\xf4', "LinReg(a+bx)","stat",     "Fits a linear regression of the form a+bx to data"),
	token(b'\xf5', "ExpReg",      "stat",     "Fits an exponential regression model to data"),
	token(b'\xf6', "LnReg",       "stat",     "Fits a logarithmic regression model to data"),
	token(b'\xf7', "PwrReg",      "stat",     "Fits a power regression model to data"),
	token(b'\xf8', "Med-Med",     "stat",     "Fits a median-median line to data"),
	token(b'\xf9', "QuadReg",     "stat",     "Fits a quadratic regression model to data"),
	token(b'\xfa', "ClrList ",    "list",     "Clears the contents of one or more lists"),
	token(b'\xfb', "ClrTable",    "io",       "Clears the function table values"),
	token(b'\xfc', "Histogram",   "stat",     "Selects the histogram plot type for a stat plot"),
	token(b'\xfd', "xyLine",      "stat",     "Selects the xy-line (connected scatter) plot type for a stat plot"),
	token(b'\xfe', "Scatter",     "stat",     "Selects the scatter plot type for a stat plot"),
	token(b'\xff', "LinReg(ax+b)","stat",     "Fits a linear regression of the form ax+b to data"),

	# Two-byte: Matrix variables 0x5C xx
	*[token(bytes([0x5c, i]), f"[{chr(0x41 + i)}]", "matrix", f"Matrix variable {chr(0x41 + i)}", alt=f"mat{chr(0x41 + i)}") for i in range(10)],

	# Two-byte: List variables 0x5D xx
	*[token(bytes([0x5d, i]), f"L{chr(0x2081 + i)}", "list", f"Built-in list variable L{i}", alt=f"L{i + 1}") for i in range(0, 6)],

	# Two-byte: Y= equation variables 0x5E xx
	*[token(
		bytes([0x5e, 0x10 + i]), 
		f"Y{chr(0x2080 + (i + 1) % 10)}", 
		"variable", 
		f"Function Y{(i + 1) % 10}", 
		alt=f"Y{(i + 1) % 10}"
	) for i in range(10)],

	*[token(
		bytes([0x5e, 0x20 + i]),
		f"{x}{chr(0x2080 + n)}ₜ", 
		"variable", 
		f"Parametric function {x}{n}", 
		alt=f"{x}{n}t"
	) for i, (n, x) in enumerate(itertools.product(range(1, 7), 'XY'))],

	*[token(
		bytes([0x5e, 0x40 + i]), 
		f"r{chr(0x2081 + i)}", 
		"variable", 
		f"Polar function r{i + 1}", 
		alt=f"r{(i + 1)}"
	) for i in range(6)],
	
	token(b'\x5e\x80', "u",   "variable", "Sequence function u",                alt="sequence-u"),
	token(b'\x5e\x81', "v",   "variable", "Sequence function v",                alt="sequence-v"),
	token(b'\x5e\x82', "w",   "variable", "Sequence function w",                alt="sequence-w"),

	# Two-byte: Picture variables 0x60 xx
	*[token(bytes([0x60, i]), f"Pic{(i + 1) % 10}", "variable", f"Picture variable Pic{(i + 1) % 10}") for i in range(10)],

	# Two-byte: GDB variables 0x61 xx
	*[token(bytes([0x61, i]), f"GDB{(i + 1) % 10}", "variable", f"Graph database variable GDB{(i + 1) % 10}") for i in range(10)],

	# Two-byte: String variables 0xAA xx (Str1=0x00 … Str9=0x08, Str0=0x09)
	*[token(bytes([0xaa, i]), f"Str{(i + 1) % 10}", "string", f"String variable Str{(i + 1) % 10}") for i in range(10)],

	# Two-byte: Statistics variables 0x62 xx
	token(b'\x62\x01', "RegEq", "stat", "The regression equation stored by the most recent regression command"),
	token(b'\x62\x02', "n",     "stat", "Number of data points used in 1-Var Stats"),
	token(b'\x62\x03', "x̄",    "stat", "Sample mean of x-values from 1-Var Stats",              alt="x-mean"),
	token(b'\x62\x04', "Σx",   "stat", "Sum of x-values from 1-Var Stats",                      alt="sum-x"),
	token(b'\x62\x05', "Σx²",  "stat", "Sum of squared x-values from 1-Var Stats",              alt="sum-x^2"),
	token(b'\x62\x06', "Sx",   "stat", "Sample standard deviation of x from 1-Var Stats"),
	token(b'\x62\x07', "σx",   "stat", "Population standard deviation of x from 1-Var Stats",   alt="sigma-x"),
	token(b'\x62\x08', "minX", "stat", "Minimum x-value from 1-Var Stats"),
	token(b'\x62\x09', "maxX", "stat", "Maximum x-value from 1-Var Stats"),
	token(b'\x62\x0a', "minY", "stat", "Minimum y-value from 2-Var Stats"),
	token(b'\x62\x0b', "maxY", "stat", "Maximum y-value from 2-Var Stats"),
	token(b'\x62\x0c', "ȳ",    "stat", "Sample mean of y-values from 2-Var Stats",              alt="y-mean"),
	token(b'\x62\x0d', "Σy",   "stat", "Sum of y-values from 2-Var Stats",                      alt="sum-y"),
	token(b'\x62\x0e', "Σy²",  "stat", "Sum of squared y-values from 2-Var Stats",              alt="sum-y^2"),
	token(b'\x62\x0f', "Sy",   "stat", "Sample standard deviation of y from 2-Var Stats"),
	token(b'\x62\x10', "σy",   "stat", "Population standard deviation of y from 2-Var Stats",   alt="sigma-y"),
	token(b'\x62\x11', "Σxy",  "stat", "Sum of x*y products from 2-Var Stats",                  alt="sum-xy"),
	token(b'\x62\x12', "r",    "stat", "Linear correlation coefficient from regression"),
	token(b'\x62\x13', "Med",  "stat", "Median value from 1-Var Stats"),
	token(b'\x62\x14', "Q1",   "stat", "First quartile (Q1) from 1-Var Stats"),
	token(b'\x62\x15', "Q3",   "stat", "Third quartile (Q3) from 1-Var Stats"),
	token(b'\x62\x16', "a",    "stat", "Regression coefficient a from the most recent regression"),
	token(b'\x62\x17', "b",    "stat", "Regression coefficient b from the most recent regression"),
	token(b'\x62\x18', "c",    "stat", "Regression coefficient c from the most recent regression"),
	token(b'\x62\x19', "d",    "stat", "Regression coefficient d from the most recent regression"),
	token(b'\x62\x1a', "e",    "stat", "Regression coefficient e from the most recent regression"),
	token(b'\x62\x1b', "x₁",  "stat", "x-value 1 from sinusoidal or other regression",           alt="x1"),
	token(b'\x62\x1c', "x₂",  "stat", "x-value 2 from sinusoidal or other regression",           alt="x2"),
	token(b'\x62\x1d', "x₃",  "stat", "x-value 3 from sinusoidal or other regression",           alt="x3"),
	token(b'\x62\x1e', "y₁",  "stat", "y-value 1 from sinusoidal or other regression",           alt="y1"),
	token(b'\x62\x1f', "y₂",  "stat", "y-value 2 from sinusoidal or other regression",           alt="y2"),
	token(b'\x62\x20', "y₃",  "stat", "y-value 3 from sinusoidal or other regression",           alt="y3"),
	token(b'\x62\x21', "n",   "stat", "Sample size n from hypothesis test output"),
	token(b'\x62\x22', "p",   "stat", "p-value from hypothesis test output"),
	token(b'\x62\x23', "z",   "stat", "z-statistic from hypothesis test output"),
	token(b'\x62\x24', "t",   "stat", "t-statistic from hypothesis test output"),
	token(b'\x62\x25', "χ²",  "stat", "Chi-squared statistic from hypothesis test output",       alt="chi2"),
	token(b'\x62\x26', "F",   "stat", "F-statistic from ANOVA or regression test output"),
	token(b'\x62\x27', "df",  "stat", "Degrees of freedom from hypothesis test output"),
	token(b'\x62\x28', "p̂",  "stat", "Estimated proportion from 1-Prop test output",            alt="p-hat"),
	token(b'\x62\x29', "p̂₁", "stat", "Estimated proportion from sample 1 in 2-Prop test",       alt="p-hat1"),
	token(b'\x62\x2a', "p̂₂", "stat", "Estimated proportion from sample 2 in 2-Prop test",       alt="p-hat2"),
	token(b'\x62\x2b', "x̄₁", "stat", "Sample mean of x from sample 1 in 2-Samp test",          alt="x-mean1"),
	token(b'\x62\x2c', "Sx₁", "stat", "Sample standard deviation from sample 1 in 2-Samp test", alt="Sx1"),
	token(b'\x62\x2d', "n₁",  "stat", "Sample size of sample 1 in 2-Samp test",                 alt="n1"),
	token(b'\x62\x2e', "x̄₂", "stat", "Sample mean of x from sample 2 in 2-Samp test",          alt="x-mean2"),
	token(b'\x62\x2f', "Sx₂", "stat", "Sample standard deviation from sample 2 in 2-Samp test", alt="Sx2"),
	token(b'\x62\x30', "n₂",  "stat", "Sample size of sample 2 in 2-Samp test",                 alt="n2"),
	token(b'\x62\x31', "Sxp", "stat", "Pooled sample standard deviation from 2-Samp t-test"),
	token(b'\x62\x32', "lower","stat", "Lower bound of a confidence interval"),
	token(b'\x62\x33', "upper","stat", "Upper bound of a confidence interval"),
	token(b'\x62\x34', "s",    "stat", "Standard deviation from a regression or test output"),
	token(b'\x62\x35', "r²",   "stat", "Coefficient of determination from regression",           alt="r^2"),
	token(b'\x62\x36', "R²",   "stat", "Coefficient of determination (alternate form)",          alt="R^2"),
	token(b'\x62\x37', "Factor df", "stat", "Degrees of freedom for the factor in one-way ANOVA",    alt="FactorDF"),
	token(b'\x62\x38', "Factor SS", "stat", "Sum of squares for the factor in one-way ANOVA",        alt="FactorSS"),
	token(b'\x62\x39', "Factor MS", "stat", "Mean square for the factor in one-way ANOVA",           alt="FactorMS"),
	token(b'\x62\x3a', "Error df",  "stat", "Degrees of freedom for the error in one-way ANOVA",     alt="ErrorDF"),
	token(b'\x62\x3b', "Error SS",  "stat", "Sum of squares for the error in one-way ANOVA",         alt="ErrorSS"),
	token(b'\x62\x3c', "Error MS",  "stat", "Mean square for the error in one-way ANOVA",            alt="ErrorMS"),

	# Two-byte: Window / Finance variables 0x63 xx
	token(b'\x63\x02', "Xscl",     "variable", "X-axis tick mark spacing for the graphing window"),
	token(b'\x63\x03', "Yscl",     "variable", "Y-axis tick mark spacing for the graphing window"),
	token(b'\x63\x0a', "Xmin",     "variable", "Minimum x-value of the graphing window"),
	token(b'\x63\x0b', "Xmax",     "variable", "Maximum x-value of the graphing window"),
	token(b'\x63\x0c', "Ymin",     "variable", "Minimum y-value of the graphing window"),
	token(b'\x63\x0d', "Ymax",     "variable", "Maximum y-value of the graphing window"),
	token(b'\x63\x0e', "Tmin",     "variable", "Minimum value of parameter T in parametric mode"),
	token(b'\x63\x0f', "Tmax",     "variable", "Maximum value of parameter T in parametric mode"),
	token(b'\x63\x10', "θmin",     "variable", "Minimum angle in polar mode",                    alt="theta-min"),
	token(b'\x63\x11', "θmax",     "variable", "Maximum angle in polar mode",                    alt="theta-max"),
	token(b'\x63\x1a', "TblStart", "variable", "Starting value for the function table"),
	token(b'\x63\x1b', "PlotStart","variable", "Starting term number for sequence plotting"),
	token(b'\x63\x1d', "nMax",     "variable", "Maximum term number for sequence graphing"),
	token(b'\x63\x1f', "nMin",     "variable", "Minimum term number for sequence graphing"),
	token(b'\x63\x21', "ΔTbl",     "variable", "Table step (increment) for the function table",  alt="dTbl"),
	token(b'\x63\x22', "Tstep",    "variable", "Step size for parameter T in parametric mode"),
	token(b'\x63\x23', "θstep",    "variable", "Step size for angle in polar mode",              alt="theta-step"),
	token(b'\x63\x26', "ΔX",       "variable", "Width of one pixel in the current graphing window", alt="dX"),
	token(b'\x63\x27', "ΔY",       "variable", "Height of one pixel in the current graphing window", alt="dY"),
	token(b'\x63\x28', "XFact",    "variable", "Zoom factor for x used by Zoom In / Zoom Out"),
	token(b'\x63\x29', "YFact",    "variable", "Zoom factor for y used by Zoom In / Zoom Out"),
	token(b'\x63\x2b', "N",        "variable", "Number of payment periods in TVM calculations"),
	token(b'\x63\x2c', "I%",       "variable", "Annual interest rate (%) for TVM calculations"),
	token(b'\x63\x2d', "PV",       "variable", "Present value for TVM calculations"),
	token(b'\x63\x2e', "PMT",      "variable", "Payment amount per period for TVM calculations"),
	token(b'\x63\x2f', "FV",       "variable", "Future value for TVM calculations"),
	token(b'\x63\x30', "P/Y",      "variable", "Payments per year for TVM calculations"),
	token(b'\x63\x31', "C/Y",      "variable", "Compounding periods per year for TVM calculations"),
	token(b'\x63\x34', "PlotStep", "variable", "Step between terms plotted in sequence graphing mode"),
	token(b'\x63\x36', "Xres",     "variable", "Graph resolution (1=every pixel, 8=every 8th pixel)"),

	# Two-byte: Graph format tokens 0x7E xx
	token(b'\x7e\x00', "Sequential", "control", "Sets graphs to plot in sequential order"),
	token(b'\x7e\x01', "Simul",      "control", "Sets graphs to plot all functions simultaneously"),
	token(b'\x7e\x02', "PolarGC",    "control", "Sets graph coordinates display to polar (r, θ) format"),
	token(b'\x7e\x03', "RectGC",     "control", "Sets graph coordinates display to rectangular (x, y) format"),
	token(b'\x7e\x04', "CoordOn",    "control", "Turns on coordinate display while tracing"),
	token(b'\x7e\x05', "CoordOff",   "control", "Turns off coordinate display while tracing"),
	token(b'\x7e\x06', "Connected",  "control", "Sets graphing to connect plotted points with line segments"),
	token(b'\x7e\x07', "Dot",        "control", "Sets graphing to plot individual points without connecting them"),
	token(b'\x7e\x08', "AxesOn",     "control", "Turns on the x- and y-axes on the graph screen"),
	token(b'\x7e\x09', "AxesOff",    "control", "Turns off the x- and y-axes on the graph screen"),
	token(b'\x7e\x0a', "GridOn",     "control", "Turns on the grid of dots on the graph screen"),
	token(b'\x7e\x0b', "GridOff",    "control", "Turns off the grid on the graph screen"),
	token(b'\x7e\x0c', "LabelOn",    "control", "Turns on axis labels (X and Y) on the graph screen"),
	token(b'\x7e\x0d', "LabelOff",   "control", "Turns off axis labels on the graph screen"),
	token(b'\x7e\x0e', "Web",        "control", "Sets sequence graphing to web (cobweb) plot format"),
	token(b'\x7e\x0f', "Time",       "control", "Sets sequence graphing to time (term vs. value) plot format"),
	token(b'\x7e\x10', "uvAxes",     "control", "Sets sequence graphing to plot u vs. v"),
	token(b'\x7e\x11', "vwAxes",     "control", "Sets sequence graphing to plot v vs. w"),
	token(b'\x7e\x12', "uwAxes",     "control", "Sets sequence graphing to plot u vs. w"),

	# Two-byte: Miscellaneous tokens 0xBB xx
	token(b'\xbb\x00', "npv(",         "math",   "Calculates net present value of a series of cash flows"),
	token(b'\xbb\x01', "irr(",         "math",   "Calculates the internal rate of return of a series of cash flows"),
	token(b'\xbb\x02', "bal(",         "math",   "Returns the balance of a loan after a specified payment number"),
	token(b'\xbb\x03', "Σprn(",        "math",   "Returns the sum of principal paid between two payment numbers", alt="sum-prn"),
	token(b'\xbb\x04', "ΣInt(",        "math",   "Returns the sum of interest paid between two payment numbers", alt="sum-int"),
	token(b'\xbb\x05', "►Nom(",        "math",   "Converts an effective interest rate to a nominal rate",        alt="to-Nom"),
	token(b'\xbb\x06', "►Eff(",        "math",   "Converts a nominal interest rate to an effective rate",        alt="to-Eff"),
	token(b'\xbb\x07', "dbd(",         "math",   "Calculates the number of days between two dates"),
	token(b'\xbb\x08', "lcm(",         "math",   "Returns the least common multiple of two integers"),
	token(b'\xbb\x09', "gcd(",         "math",   "Returns the greatest common divisor of two integers"),
	token(b'\xbb\x0a', "randInt(",     "math",   "Generates a uniformly random integer between two bounds"),
	token(b'\xbb\x0b', "randBin(",     "math",   "Generates a random integer from a binomial distribution"),
	token(b'\xbb\x0c', "sub(",         "string", "Extracts a substring from a string"),
	token(b'\xbb\x0d', "stdDev(",      "stat",   "Returns the sample standard deviation of a list"),
	token(b'\xbb\x0e', "variance(",    "stat",   "Returns the sample variance of a list"),
	token(b'\xbb\x0f', "inString(",    "string", "Returns the position of a substring within a string"),
	token(b'\xbb\x10', "normalcdf(",   "stat",   "Computes the normal distribution CDF between two bounds"),
	token(b'\xbb\x11', "invNorm(",     "stat",   "Returns the inverse normal (z-score) for a given area"),
	token(b'\xbb\x12', "tcdf(",        "stat",   "Computes the Student's t distribution CDF between two bounds"),
	token(b'\xbb\x13', "χ²cdf(",       "stat",   "Computes the chi-squared distribution CDF between two bounds", alt="chi2cdf"),
	token(b'\xbb\x14', "Fcdf(",        "stat",   "Computes the F distribution CDF between two bounds"),
	token(b'\xbb\x15', "binompdf(",    "stat",   "Computes the binomial probability for a given number of successes"),
	token(b'\xbb\x16', "binomcdf(",    "stat",   "Computes the cumulative binomial probability"),
	token(b'\xbb\x17', "poissonpdf(",  "stat",   "Computes the Poisson probability for a given number of events"),
	token(b'\xbb\x18', "poissoncdf(",  "stat",   "Computes the cumulative Poisson probability"),
	token(b'\xbb\x19', "geometpdf(",   "stat",   "Computes the geometric probability for the first success on trial k"),
	token(b'\xbb\x1a', "geometcdf(",   "stat",   "Computes the cumulative geometric probability up to trial k"),
	token(b'\xbb\x1b', "normalpdf(",   "stat",   "Computes the normal probability density at a given value"),
	token(b'\xbb\x1c', "tpdf(",        "stat",   "Computes the Student's t probability density at a given value"),
	token(b'\xbb\x1d', "χ²pdf(",       "stat",   "Computes the chi-squared probability density at a given value", alt="chi2pdf"),
	token(b'\xbb\x1e', "Fpdf(",        "stat",   "Computes the F distribution probability density at a given value"),
	token(b'\xbb\x1f', "randNorm(",    "math",   "Generates a random number from a normal distribution"),
	token(b'\xbb\x20', "tvm_Pmt",      "math",   "Computes the payment amount for a TVM calculation"),
	token(b'\xbb\x21', "tvm_I%",       "math",   "Computes the interest rate for a TVM calculation"),
	token(b'\xbb\x22', "tvm_PV",       "math",   "Computes the present value for a TVM calculation"),
	token(b'\xbb\x23', "tvm_N",        "math",   "Computes the number of periods for a TVM calculation"),
	token(b'\xbb\x24', "tvm_FV",       "math",   "Computes the future value for a TVM calculation"),
	token(b'\xbb\x25', "conj(",        "math",   "Returns the complex conjugate of a complex number"),
	token(b'\xbb\x26', "real(",        "math",   "Returns the real part of a complex number"),
	token(b'\xbb\x27', "imag(",        "math",   "Returns the imaginary part of a complex number"),
	token(b'\xbb\x28', "angle(",       "math",   "Returns the polar angle (argument) of a complex number"),
	token(b'\xbb\x29', "cumSum(",      "list",   "Returns a list of cumulative sums from a list"),
	token(b'\xbb\x2a', "expr(",        "string", "Evaluates a string as a mathematical expression"),
	token(b'\xbb\x2b', "length(",      "string", "Returns the number of characters in a string"),
	token(b'\xbb\x2c', "ΔList(",       "list",   "Returns a list of first differences of a list",           alt="dList("),
	token(b'\xbb\x2d', "ref(",         "matrix", "Reduces a matrix to row-echelon form"),
	token(b'\xbb\x2e', "rref(",        "matrix", "Reduces a matrix to reduced row-echelon form"),
	token(b'\xbb\x2f', "►Rect",        "math",   "Converts a complex number from polar to rectangular display", alt="to-Rect"),
	token(b'\xbb\x30', "►Polar",       "math",   "Converts a complex number from rectangular to polar display", alt="to-Polar"),
	token(b'\xbb\x31', "𝑒",            "math",   "The mathematical constant e (≈2.71828...)"),
	token(b'\xbb\x32', "SinReg",       "stat",   "Fits a sinusoidal regression model to data"),
	token(b'\xbb\x33', "Logistic",     "stat",   "Fits a logistic regression model to data"),
	token(b'\xbb\x34', "LinRegTTest",  "stat",   "Performs a linear regression t-test"),
	token(b'\xbb\x35', "ShadeNorm(",   "stat",   "Shades the area under a normal curve between two bounds on the graph"),
	token(b'\xbb\x36', "Shade_t(",     "stat",   "Shades the area under a t distribution curve between two bounds"),
	token(b'\xbb\x37', "Shadeχ²(",     "stat",   "Shades the area under a chi-squared curve between two bounds", alt="shade-chi^2"),
	token(b'\xbb\x38', "ShadeF(",      "stat",   "Shades the area under an F distribution curve between two bounds"),
	token(b'\xbb\x39', "Matr►list(",   "matrix", "Copies columns of a matrix into lists",                  alt="Matr-to-list"),
	token(b'\xbb\x3a', "List►matr(",   "list",   "Fills columns of a matrix from lists",                   alt="List-to-matr"),
	token(b'\xbb\x3b', "Z-Test(",      "stat",   "Performs a one-sample z-test for a mean"),
	token(b'\xbb\x3c', "T-Test",       "stat",   "Performs a one-sample t-test for a mean"),
	token(b'\xbb\x3d', "2-SampZTest(", "stat",   "Performs a two-sample z-test comparing two means"),
	token(b'\xbb\x3e', "1-PropZTest(", "stat",   "Performs a one-proportion z-test"),
	token(b'\xbb\x3f', "2-PropZTest(", "stat",   "Performs a two-proportion z-test"),
	token(b'\xbb\x40', "χ²-Test(",     "stat",   "Performs a chi-squared test for association on a matrix", alt="chi^2-test"),
	token(b'\xbb\x41', "ZInterval",    "stat",   "Computes a one-sample z confidence interval for a mean"),
	token(b'\xbb\x42', "2-SampZInt(",  "stat",   "Computes a two-sample z confidence interval"),
	token(b'\xbb\x43', "1-PropZInt(",  "stat",   "Computes a one-proportion z confidence interval"),
	token(b'\xbb\x44', "2-PropZInt(",  "stat",   "Computes a two-proportion z confidence interval"),
	token(b'\xbb\x45', "GraphStyle(",  "control","Sets the line style for a Y= function"),
	token(b'\xbb\x46', "2-SampTTest",  "stat",   "Performs a two-sample t-test comparing two means"),
	token(b'\xbb\x47', "2-SampFTest",  "stat",   "Performs an F-test comparing two population variances"),
	token(b'\xbb\x48', "TInterval",    "stat",   "Computes a one-sample t confidence interval for a mean"),
	token(b'\xbb\x49', "2-SampTInt",   "stat",   "Computes a two-sample t confidence interval"),
	token(b'\xbb\x4a', "SetUpEditor ",  "list",   "Sets up the stat list editor with specified lists"),
	token(b'\xbb\x4b', "Pmt_End",      "math",   "Sets TVM payments to occur at end of period"),
	token(b'\xbb\x4c', "Pmt_Bgn",      "math",   "Sets TVM payments to occur at beginning of period"),
	token(b'\xbb\x4d', "Real",         "control","Sets the calculator to real-number mode"),
	token(b'\xbb\x4e', "re^θi",        "control","Sets the calculator to polar complex-number mode",        alt=('re^theta-i', "polar_complex")),
	token(b'\xbb\x4f', "a+bi",         "control","Sets the calculator to rectangular complex-number mode",  alt="rect_complex"),
	token(b'\xbb\x50', "ExprOn",       "control","Turns on expression display during tracing"),
	token(b'\xbb\x51', "ExprOff",      "control","Turns off expression display during tracing"),
	token(b'\xbb\x52', "ClrAllLists",  "list",   "Clears all list variables in memory"),
	token(b'\xbb\x53', "GetCalc(",     "io",     "Retrieves a variable from a linked calculator"),
	token(b'\xbb\x54', "DelVar ",       "variable","Deletes a variable from memory"),
	token(b'\xbb\x55', "Equ►String(",  "string", "Converts a Y= equation variable to a string",            alt="Equ-to-Str"),
	token(b'\xbb\x56', "String►Equ(",  "string", "Stores a string into a Y= equation variable",            alt="Str-to-Equ"),
	token(b'\xbb\x57', "Clear Entries","io",     "Clears the calculator's entry history",                   alt="ClearEntries"),
	token(b'\xbb\x58', "Select(",      "list",   "Selects elements of two lists based on a stat plot selection"),
	token(b'\xbb\x59', "ANOVA(",       "stat",   "Performs a one-way analysis of variance on two or more lists"),
	token(b'\xbb\x5a', "ModBoxplot",   "stat",   "Selects the modified box-and-whisker plot type (shows outliers)"),
	token(b'\xbb\x5b', "NormProbPlot", "stat",   "Selects the normal probability plot type for a stat plot"),
	token(b'\xbb\x64', "G-T",          "control","Sets the screen to graph-table split mode"),
	token(b'\xbb\x65', "ZoomFit",      "io",     "Adjusts the y-window to fit the function given the current x-window"),
	token(b'\xbb\x66', "DiagnosticOn", "stat",   "Turns on display of r and r² in regression output"),
	token(b'\xbb\x67', "DiagnosticOff","stat",   "Turns off display of r and r² in regression output"),
	token(b'\xbb\x68', "Archive ",     "variable","Moves a variable from RAM to the archive (Flash) memory"),
	token(b'\xbb\x69', "UnArchive ",   "variable","Moves a variable from archive memory back to RAM"),
	token(b'\xbb\x6a', "Asm(",         "control","Executes an assembly language program"),
	token(b'\xbb\x6b', "AsmComp(",     "control","Compiles a tokenized assembly source program"),
	token(b'\xbb\x6c', "AsmPrgm",      "control","Marker token indicating an assembly program"),
	token(b'\xbb\x6d', "compiled asm", "control","?"),

	# Accented Latin characters (0xBB6E–0xBB99; 0xBB7E unused — uppercase I-acute absent)
	*[token(bytes([0xBB, b]), ch, "string", name, alt=name)
		for b, ch, name in [
			(0x6e, "Á", "A-acute"),    (0x6f, "À", "A-grave"),    (0x70, "Â", "A-circumflex"), (0x71, "Ä", "A-umlaut"),
			(0x72, "á", "a-acute"),    (0x73, "à", "a-grave"),    (0x74, "â", "a-circumflex"), (0x75, "ä", "a-umlaut"),
			(0x76, "É", "E-acute"),    (0x77, "È", "E-grave"),    (0x78, "Ê", "E-circumflex"), (0x79, "Ë", "E-umlaut"),
			(0x7a, "é", "e-acute"),    (0x7b, "è", "e-grave"),    (0x7c, "ê", "e-circumflex"), (0x7d, "ë", "e-umlaut"),
			(0x7f, "Ì", "I-grave"),    (0x80, "Î", "I-circumflex"),(0x81, "Ï", "I-umlaut"),
			(0x82, "í", "i-acute"),    (0x83, "ì", "i-grave"),    (0x84, "î", "i-circumflex"), (0x85, "ï", "i-umlaut"),
			(0x86, "Ó", "O-acute"),    (0x87, "Ò", "O-grave"),    (0x88, "Ô", "O-circumflex"), (0x89, "Ö", "O-umlaut"),
			(0x8a, "ó", "o-acute"),    (0x8b, "ò", "o-grave"),    (0x8c, "ô", "o-circumflex"), (0x8d, "ö", "o-umlaut"),
			(0x8e, "Ú", "U-acute"),    (0x8f, "Ù", "U-grave"),    (0x90, "Û", "U-circumflex"), (0x91, "Ü", "U-umlaut"),
			(0x92, "ú", "u-acute"),    (0x93, "ù", "u-grave"),    (0x94, "û", "u-circumflex"), (0x95, "ü", "u-umlaut"),
			(0x96, "Ç", "C-cedilla"),  (0x97, "ç", "c-cedilla"),
			(0x98, "Ñ", "N-tilde"),    (0x99, "ñ", "n-tilde"),
		]],
	
	token(b'\xbb\x9a', "´", "string", "Acute accent", alt="acute-accent"),
	token(b'\xbb\x9b', "`", "string", "Grave accent", alt="grave-accent"),
	token(b'\xbb\x9c', "¨", "string", "Diaeresis / umlaut accent", alt="umlaut-accent"),
	token(b'\xbb\x9d', "¿", "string", "Inverted question mark", alt="?-inverted"),
	token(b'\xbb\x9e', "¡", "string", "Inverted exclamation mark", alt="!-inverted"),
	token(b'\xbb\x9f', "α", "string", "alpha",  alt="alpha"),
	token(b'\xbb\xa0', "β", "string", "beta",   alt="beta"),
	token(b'\xbb\xa1', "γ", "string", "gamma",  alt="gamma"),
	token(b'\xbb\xa2', "Δ", "string", "Delta",  alt="Delta"),
	token(b'\xbb\xa3', "δ", "string", "delta",  alt="delta"),
	token(b'\xbb\xa4', "ε", "string", "epsilon", alt="epsilon"),
	token(b'\xbb\xa5', "λ", "string", "lambda", alt="lambda"),
	token(b'\xbb\xa6', "μ", "string", "mu",     alt="mu"),
	token(b'\xbb\xa7', "π", "string", "pi (non-mathematical)", alt="pi-non-math"),  # deprecated
	token(b'\xbb\xa8', "ρ", "string", "rho",    alt="rho"),
	token(b'\xbb\xa9', "Σ", "string", "Sigma",  alt="Sigma"),
	token(b'\xbb\xab', "φ", "string", "phi",    alt="phi"),
	token(b'\xbb\xac', "Ω", "string", "Omega",  alt="Omega"),
	token(b'\xbb\xad', "ψ", "string", "Greek psi", alt="psi"),
	token(b'\xbb\xae', "χ", "string", "chi",    alt="chi"),
	token(b'\xbb\xaf', "F", "string", "Italic F used in F-statistic display"),
	
	# Lowercase letters a–k (0xBBB0–0xBBBA; 0xBBBB is unused)
	*[token(bytes([0xBB, 0xB0 + i]), chr(0x61 + i), "string", f"Lowercase {chr(0x61 + i)}", key=chr(0x61 + i)) for i in range(11)],
	# Lowercase letters l–z (0xBBBC–0xBBCA)
	*[token(bytes([0xBB, 0xBC + i]), chr(0x6C + i), "string", f"Lowercase {chr(0x6C + i)}", key=chr(0x6C + i)) for i in range(15)],
	
	token(b'\xbb\xcb', "σ", "string", "sigma (statistics display)", alt="sigma"),
	token(b'\xbb\xcc', "τ", "string", "tau (display character)", alt="tau"),
	token(b'\xbb\xcd', "Í", "string", "I-acute (extended)", alt="I-acute"),
	token(b'\xbb\xce', "GarbageCollect","variable","Defragments archive memory to recover space"),
	token(b'\xbb\xcf', "~",  "string", "Tilde character", alt="tilde"),
	token(b'\xbb\xd1', "@",  "string", "At sign",       alt="at-sign",   key='@'),
	token(b'\xbb\xd2', "#",  "string", "Number/hash sign", alt="hash",   key='#'),
	token(b'\xbb\xd3', "$",  "string", "Dollar sign",   alt="dollar",    key='$'),
	token(b'\xbb\xd4', "&",  "string", "Ampersand",     alt="ampersand", key='&'),
	token(b'\xbb\xd5', "`",  "string", "Grave/backtick",alt="backtick"),
	token(b'\xbb\xd6', ";",  "string", "Semicolon",     alt="semicolon", key=';'),
	token(b'\xbb\xd7', "\\", "string", "Backslash",     alt="backslash", key='\\'),
	token(b'\xbb\xd8', "|",  "string", "Pipe/vertical bar", alt="pipe",  key='|'),
	token(b'\xbb\xd9', "_",  "string", "Underscore",    alt="underscore",key='_'),
	token(b'\xbb\xda', "%",  "string", "Percent sign",  alt="percent",   key='%'),
	token(b'\xbb\xdb', "…",  "string", "Ellipsis",      alt="ellipsis"),
	token(b'\xbb\xdc', "∠", "string", "Angle symbol", alt="angle"),
	token(b'\xbb\xdd', "ß", "string", "German sharp S", alt="sharp-s"),
	token(b'\xbb\xde', "x", "string", "Superscript x", alt="superscript-x"),  # deprecated
	token(b'\xbb\xdf', "T", "string", "Subscript T", alt="subscript-t"),  # deprecated
	
	*[token(bytes([0xBB, 0xE0 + i]), chr(0x2080 + i), "string", "Subscript {i}", alt=f"subscript-{i}") for i in range(11)],
	
	token(b'\xbb\xeb', "←", "string", "Left arrow",   alt="left-arrow"),
	token(b'\xbb\xec', "→", "string", "Right arrow", alt="right-arrow"),
	token(b'\xbb\xed', "↑", "string", "Up arrow",     alt="up-arrow"),
	token(b'\xbb\xee', "↓", "string", "Down arrow",   alt="down-arrow"),
	token(b'\xbb\xf0', "x", "string", "x"),  # deprecated
	token(b'\xbb\xf1', "∫", "string", "Integral symbol", alt="integral"),
	token(b'\xbb\xf2', "🡅", "string", "scroll up"),
	token(b'\xbb\xf3', "🡇", "string", "scroll down"),
	token(b'\xbb\xf4', "√", "string", "Square root symbol", alt="root"),  # deprecated
	token(b'\xbb\xf5', "<funcon>", "string", "Function On", alt='function-on'),  # deprecated

	# Two-byte: TI-84+ extended tokens 0xEF xx
	# 0xEF00–0xEF0F and 0xEF10–0xEF1E: original TI-84+ OS; 0xEF17–0xEF1E also on TI-84+ non-CE newer OS
	# 0xEF30–0xEF3D: TI-84 Plus (non-CE) newer OS only
	token(b'\xef\x00', "setDate(",      "io",      "Sets the date on the clock of an OS-enabled calculator"),
	token(b'\xef\x01', "setTime(",      "io",      "Sets the time on the clock of an OS-enabled calculator"),
	token(b'\xef\x02', "checkTmr(",     "io",      "Returns the elapsed time in seconds since startTmr was called"),
	token(b'\xef\x03', "setDtFmt(",     "io",      "Sets the date display format (M/D/Y, D/M/Y, or Y/M/D)"),
	token(b'\xef\x04', "setTmFmt(",     "io",      "Sets the time display format (12-hour or 24-hour)"),
	token(b'\xef\x05', "timeCnv(",      "math",    "Converts a number of seconds into a {days,hours,min,sec} list"),
	token(b'\xef\x06', "dayOfWk(",      "math",    "Returns the day of the week (1=Sun … 7=Sat) for a given date"),
	token(b'\xef\x07', "getDtStr",      "io",      "Returns the current date as a string in the active format"),
	token(b'\xef\x08', "getTmStr(",     "io",      "Returns the current time as a string in the active format"),
	token(b'\xef\x09', "getDate",       "io",      "Returns the current date as a {year, month, day} list"),
	token(b'\xef\x0a', "getTime",       "io",      "Returns the current time as a {hour, minute, second} list"),
	token(b'\xef\x0b', "startTmr",      "io",      "Starts a timer and returns a reference value for checkTmr("),
	token(b'\xef\x0c', "getDtFmt",      "io",      "Returns the current date format setting as a number"),
	token(b'\xef\x0d', "getTmFmt",      "io",      "Returns the current time format setting as a number"),
	token(b'\xef\x0e', "isClockOn",     "io",      "Returns 1 if the clock is currently on, 0 if off"),
	token(b'\xef\x0f', "ClockOff",      "io",      "Turns off the clock on OS-enabled calculators"),
	token(b'\xef\x10', "ClockOn",       "io",      "Turns on the clock on OS-enabled calculators"),
	token(b'\xef\x11', "OpenLib(",      "io",      "Opens an application library for use with ExecLib"),
	token(b'\xef\x12', "ExecLib",       "io",      "Executes a routine from a library opened with OpenLib("),
	token(b'\xef\x13', "invT(",         "stat",    "Returns the inverse t-distribution value for a given area and degrees of freedom"),
	token(b'\xef\x14', "χ²GOF-Test(",   "stat",    "Performs a chi-squared goodness-of-fit test",              alt="chi^2-GOF-Test"),
	token(b'\xef\x15', "LinRegTInt",    "stat",    "Computes a linear regression t confidence interval"),
	token(b'\xef\x16', "Manual-Fit",    "stat",    "Fits a line manually to a scatter plot by dragging"),
	token(b'\xef\x17', "ZQuadrant1",    "control", "Zoom preset: zooms to show only quadrant 1"),
	token(b'\xef\x18', "ZFrac1/2",      "control", "Zoom preset: sets window for fractions with denominator 2"),
	token(b'\xef\x19', "ZFrac1/3",      "control", "Zoom preset: sets window for fractions with denominator 3"),
	token(b'\xef\x1a', "ZFrac1/4",      "control", "Zoom preset: sets window for fractions with denominator 4"),
	token(b'\xef\x1b', "ZFrac1/5",      "control", "Zoom preset: sets window for fractions with denominator 5"),
	token(b'\xef\x1c', "ZFrac1/8",      "control", "Zoom preset: sets window for fractions with denominator 8"),
	token(b'\xef\x1d', "ZFrac1/10",     "control", "Zoom preset: sets window for fractions with denominator 10"),
	token(b'\xef\x1e', "mathprintbox",  "io",      "Draws a MathPrint-style box around an expression"),
	token(b'\xef\x30', "►n/d◄►Un/d",   "operator","Converts between proper fraction and mixed number display"),
	token(b'\xef\x31', "►F◄►D",         "operator","Converts between fraction and decimal display"),
	token(b'\xef\x32', "remainder(",    "math",    "Returns the remainder of integer division"),
	token(b'\xef\x33', "Σ(",            "math",    "Summation: evaluates an expression over a range of integer values", alt='sigma('),
	token(b'\xef\x34', "logBASE(",      "math",    "Returns the logarithm of a value in a specified base"),
	token(b'\xef\x35', "randIntNoRep(", "math",    "Returns a list of non-repeating random integers in a range"),
	token(b'\xef\x36', "MATHPRINT",     "control", "Mode setting: enables MathPrint display mode"),
	token(b'\xef\x37', "CLASSIC",       "control", "Mode setting: enables Classic (linear) display mode"),
	token(b'\xef\x38', "n/d",           "operator","Fraction template: enters a proper fraction"),
	token(b'\xef\x39', "Un/d",          "operator","Fraction template: enters a mixed number"),
	token(b'\xef\x3a', "AUTO",          "control", "Mode setting: sets fraction display to AUTO"),
	token(b'\xef\x3b', "DEC",           "control", "Mode setting: sets fraction display to DEC (decimal)"),
	token(b'\xef\x3c', "FRAC",          "control", "Mode setting: sets fraction display to FRAC"),
	token(b'\xef\x3d', "FRAC-APPROX",   "control", "Mode setting: sets fraction display to FRAC-APPROX"),

]

if __name__ == '__main__':
	@dataclass
	class NullToken:
		code: bytes
	
	check = [None] * 0x100
	check_misc = [None] * 0xF6
	duplicate = set()
	
	for code in [
		b'\x00', b'\x26', b'\x5c', b'\x5d', b'\x5e', b'\x60', b'\x61', b'\x62', b'\x63', b'\x7e', b'\xaa', b'\xbb', b'\xef',
		b'\xbb\x5c', b'\xbb\x5d', b'\xbb\x5e', b'\xbb\x5f', b'\xbb\x60', b'\xbb\x61', b'\xbb\x62', b'\xbb\x63', b'\xbb\x7e', b'\xbb\xaa', b'\xbb\xbb', b'\xbb\xd0', b'\xbb\xef', 
	]:
		old_len = len(duplicate)
		duplicate.add(code)
		if old_len == len(duplicate):
			raise ValueError(f"Duplicate: {token}")
		if len(code) == 1:
			check[code[0]] = NullToken(code)
		elif code[0] == 0xBB:
			check_misc[code[1]] = NullToken(code)
	
	for token in TOKENS:
		old_len = len(duplicate)
		duplicate.add(token.code)
		if old_len == len(duplicate):
			raise ValueError(f"Duplicate: {token}")
		if len(token.code) == 1:
			check[token.code[0]] = token
		elif token.code[0] == 0xBB:
			check_misc[token.code[1]] = token
	
	for i, token in enumerate(check):
		if token is None:
			print('MISSING:', hex(i))
	
	for i, token in enumerate(check_misc):
		if token is None:
			print('MISSING:', hex(0xBB00 + i))
